### ISSUE TITLE
Consider moving Kafka logs

### ISSUE THREAD

**Issue by dcode** [CyberAnalyticDevTeam/SimpleRock#1]
By default, Kafka dumps topic data to `/tmp/kafka-logs`. This is....not exactly good. Should consider moving to `/data/kafka` to be consistent and make it easier to allocate data space.

This is set in `/opt/kafka/config/server.properties`.

Propose change:
~~~~~~~
log.dirs=/tmp/kafka-logs
~~~~~~~

to

~~~~~~~
log.dirs=/data/kafka
~~~~~~~

**Comment by jeffgeiger** [comment]
Fixed with commit  c109cb6.
