### ISSUE TITLE
Option for higher-speed Ethernet interface

### ISSUE THREAD

**Issue by charlesfair** [CyberAnalyticDevTeam/SimpleRock#10]
Need option for optimized settings for higher-speed monitoring interface if used for sniffing - 10GB Ethernet. 
If this is best done/tweaked AFTER installation, then we should document in the Wiki.

**Comment by charlesfair** [comment]
* This is a lower priority issue than "Specify an Ethernet Interface"

**Comment by dcode** [comment]
The optimum settings for a 10 gig interface aren't much different than a 1 gig interface....it all comes down to where the choke point is and is _VERY_ hardware specific. The interface config script is almost always going to be the same, the only things you might change are some buffer sizes in the way that some tools process data.

SimpleROCK cannot purport to support perfectly tuned production collection systems at high data rates. That requires careful planning, testing, and tuning from an experienced engineer and cannot be completely automated at this time. SimpleROCK gets you 90% there, which is Good Enough<sup>TM</sup> for home sensors, labs, and range use. The remaining 10% is [NP-hard](https://en.wikipedia.org/wiki/NP-hardness).

Marking candidate for wontfix.

**Comment by charlesfair** [comment]
Thought the settings were radically different, great base design!

**Comment by dcode** [comment]
The same setting is: "Copy these bits as fast as you can to over there."

_"...as fast as you can..."_ depends on the hardware.
