### ISSUE TITLE
Change initial Ethernet monitoring interfaces from 1, to 2-4, before and after installation

### ISSUE THREAD

**Issue by charlesfair** [CyberAnalyticDevTeam/SimpleRock#13]
Upon setup, would like to have the option to monitor 2-4 Ethernet interfaces instead of the default single interface.  How would this be done after installation?

**Comment by dcode** [comment]
@charlesfair at this point, this is beyond the scope of SimpleROCK. The current deployment mechanism is designed for initial low-complexity environments. That said, it is a great starting point for deploying more complex situations.

This is on the roadmap, but down the road. We have many more core features to improve before we start trying to adapt to every environment.
