### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by charlesfair** [CyberAnalyticDevTeam/SimpleRock#15]
Apparently, the install fails with Bro (full transcript attached).  

[rock_install_fail_20160119.txt](https://github.com/CyberAnalyticDevTeam/SimpleRock/files/95525/rock_install_fail_20160119.txt)

**Comment by dcode** [comment]
Did you build bro with Myricom support? Your error is:

```
/opt/bro/bin/bro: error while loading shared libraries: libsnf.so.0: cannot open shared object file: No such file or directory
```

SimpleRock doesn't provide libsnf.so as SNF is the [Myricom sniffing driver](https://www.myricom.com/sniffer.html)

**Comment by jeffgeiger** [comment]
Fixed in PR 16.
