### ISSUE TITLE
pf_ring Failures

### ISSUE THREAD

**Issue by peasead** [CyberAnalyticDevTeam/SimpleRock#20]
It appears that pf_ring is preventing the monitor interface from starting (or staying up). The install appeared to work properly, all the other services are working.

Troubleshooting:
* reboot
* restart interface
* manually stop/start pf_ring
* cursed
* stopped ROCK via `rock_stop`
* started ROCK via `rock_start`
* "Basic Troubleshooting" from rocknsm.io

Output from `rock_status`
```
[root@simplerockbuild ~]# rock_status
 ✗ Check each monitor interface is live
   (in test file /usr/local/bin/rock_status, line 24)
     `[ $packets -gt 0 ]' failed
   eno33554960 had 0 packets in 5 secs.
 ✓ Check for interface errors
 ✓ Check monitor interface for tx packets
 ✓ Check PF_RING settings
 ✓ Check that broctl is running
 ✓ Check for bro-detected packet loss
 ✓ Check that zookeeper is running
 ✓ Check that zookeeper is listening
 ✓ Check that client can connect to zookeeper
 ✓ Check that kafka is running
 ✓ Check that kafka is connected to zookeeper
 ✓ Check that logstash is running
 ✓ Check that elasticsearch is running
 ✓ Check that kibana is running

14 tests, 1 failure
```

[systemctl log](https://file.io/lJJSTm)
[journal log](https://file.io/vUOlNj)

**Comment by dcode** [comment]
Your output from rock_status merely suggests that there are no packets on the link. Is the link live?

**Comment by peasead** [comment]
This isn't a failure of pf_ring, it's just now it is configured to operate. pf_ring only reads received packets, not transmitted packets, which is how tcpreplay works.

To use SimpleRock to send your previously collected traffic through (tcpreplay):
```
# rock_stop
# ifdown [capture interface]
# modprobe -r pf_ring; modprobe pf_ring <- resets the RX only flag
# cat /proc/net/pf_ring/info <- validate that "Capture TX" is present
# ifup [capture interface]
# rock_start
# rock_status
```
`rock_status` will show incorrect pf_ring settings, capture interface is set to TX, and that the monitor interface still isn't live (because you're not actively tapping); but should show all the other services up and running. 

You should be able to populate `/data/bro/logs/current`, as expected, with this:
`# tcpreplay -t -i [capture interface] [collected_packets.pcap]`

H/T @dcode

**Comment by charlesfair** [comment]
From Jeff Geiger earlier today:  

PF_RING is disabled by default, as the dcode intended, and tcpreplay will not be able to send traffic.  To enable:

1.  Edit "/etc/pf_ring/pf_ring.conf"
2.  Change line 3 to "1" as in:  "enable_tx_capture=1"
3.  Must restart to enable change

tcpreplay now works fine.  Reasoning behind this configuration is it's "normally" set to off to prevent inadvertent data leakage during an incident response engagement.
