### ISSUE TITLE
Update Wiki (or readme) with enabling tcpreplay procedure for testing

### ISSUE THREAD

**Issue by charlesfair** [CyberAnalyticDevTeam/SimpleRock#26]
Update Wiki (or readme) with enabling tcpreplay procedure for testing:

vi /etc/pf_ring/pf_ring.conf

change enable_tx_capture to "1" 

Restart system 

* I am not sure if there is a way to do this without a restart

**Comment by dcode** [comment]
I'd recommend we actually put this into a script perhaps. This is related to issue #27. The script can make the changes and reload the module. No need to reboot the box, but you do have to stop the collection processes that use PF_RING and bring the interface down.

**Comment by jeffgeiger** [comment]
This was handled by @peasead's PR.  See the training_mode and production_mode scripts.
