### ISSUE TITLE
Marvel and Kibana Mismatch

### ISSUE THREAD

**Issue by somestranger** [CyberAnalyticDevTeam/SimpleRock#29]
plugin:marvel 	Marvel version 2.2.0 is not supported with Kibana 4.3.1 
error on current build of the ROCK

**Comment by jeffgeiger** [comment]
Please test now that we've merged PR #34.  It's working in my testing.

**Comment by slightner11** [comment]
fixed.

**Comment by jeffgeiger** [comment]
Fix verified by third party.
