### ISSUE TITLE
Update Elastic stack logos in diagrams

### ISSUE THREAD

**Issue by ycombinator** [CyberAnalyticDevTeam/SimpleRock#33]
Super low priority request but I noticed that a couple of the diagrams under https://github.com/CyberAnalyticDevTeam/SimpleRock/tree/gh-pages/images are using outdated logos for Elasticsearch, Logstash, and Kibana. The most recent product logos are available at https://www.elastic.co/brand. Thanks!

**Comment by jeffgeiger** [comment]
Closed with PR #35.  Thanks for the heads up!
