### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by cyberhannibal** [CyberAnalyticDevTeam/SimpleRock#40]
After installing SimpleRock per the instructions on Github and trying to execute rock_start, I get error "command not found."  Error codes at the end of installation may give a clue.  Screen shot attached.
![image](https://cloud.githubusercontent.com/assets/18199287/14192416/26fd1e9e-f763-11e5-966c-d5f0f3e9f390.png)

**Comment by dcode** [comment]
Looks like a version mismatch with the recent Elasticsearch releases causing this to fail. Will probably get to it this weekend. Thanks for the screenshot of the errors!

**Comment by jeffgeiger** [comment]
Updated the versions and hashes for the latest ES.  Good catch.

**Comment by cyberhannibal** [comment]
It works. Thanks!

Tony Kirtley
